SET FOREIGN_KEY_CHECKS=0;
INSERT INTO recipes (title, ingredients, img, duration, portions, preparation, category_id) VALUES ('Pasta al pomodoro', 'Pasta, pomodoro, olio, sale', 'https://tuttofabrodoincucina.it/wp-content/uploads/2022/10/PASTA-AL-SUGO-DI-POMODORO-FRESCO-EV1.jpg', 30, 4, 'Praesent arcu accumsan porta sollicitudin a commodo arcu sociis. Id venenatis eleifend ac curae;. Nullam scelerisque scelerisque tellus ligula. Auctor fusce mattis pellentesque ridiculus placerat aptent magnis. Id sociis suspendisse tempor.', 2);
INSERT INTO recipes (title, ingredients, img, duration, portions, preparation, category_id ) VALUES ('Pizza margherita', 'Farina ,acqua, sale, lievito, pomodoro, mozzarella', 'https://www.tavolartegusto.it/wp/wp-content/uploads/2020/05/Pizza-napoletana-Ricetta-della-Pizza-Napoletana-Pizza-Margherita.jpg', 45, 3, 'Praesent arcu accumsan porta sollicitudin a commodo arcu sociis. Id venenatis eleifend ac curae;. Nullam scelerisque scelerisque tellus ligula. Auctor fusce mattis pellentesque ridiculus placerat aptent magnis. Id sociis suspendisse tempor. ', 2);
INSERT INTO recipes (title, ingredients, img, duration, portions, preparation, category_id) VALUES ('cotoletta', 'Vitello ,parmigiano, uova, latte, olio, sale', 'https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/03/3190_Cotoletta.jpg?resize=895%2C616&ssl=1', 60, 2, 'Praesent arcu accumsan porta sollicitudin a commodo arcu sociis. Id venenatis eleifend ac curae;. Nullam scelerisque scelerisque tellus ligula. Auctor fusce mattis pellentesque ridiculus placerat aptent magnis. Id sociis suspendisse tempor. ', 3);
INSERT INTO categories (name) VALUE('Antipasto')
INSERT INTO categories (name) VALUE('Primo')
INSERT INTO categories (name) VALUE('Secondo')
INSERT INTO categories (name) VALUE('Contorno')
INSERT INTO categories (name) VALUE('Dolce')
